### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/GeoHelper-Front#9]
Была сделана таблица. К ней прикручена пагинация. Всё красиво. (Пока всё не в мастере.)

С точки зрения дизайна и здравого смысла страница не вынесет больше 11 кнопок в ряд, а если помнить про фолд, то там и 5 - уже проблема. Сейчас при количестве объектов более 165 страница будет выглядеть не так красиво.

**Требуется:** продумать поведение для блока с пагинацией особенно все эти многоточия и никому не нужные раскладушки.

![image](https://user-images.githubusercontent.com/23360152/139557385-3fe6595c-e8d6-4d82-b0b0-5d6fe8b20653.png)

**Comment by Eloren1** [comment]
Так ли нужна вкладка «Файлы», когда там просто не особо полезные названия, и в общем-то все? Как минимум можно убрать это в popup window
И интересно, как выглядит интерфейс на смартфонах

**Comment by CAPCHIK** [comment]
Не могу не посоветовать пример элемента пагинации https://ant.design/components/pagination/

**Comment by IvLaptev** [comment]
Закрыто по причине отказа от первоначальной идеи
